apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  GRAFANA_ADMIN_PASSWORD: 5astmetrics100
  GRAFANA_ADMIN_USER: admin
  GRAFANA_CONTAINER: grafana
  GRAFANA_HOST: localhost
  GRAFANA_PORT: "3000"
  POSTGRES_CONTAINER: timescaledb
  POSTGRES_DBNAME: timedb
  POSTGRES_HOST: localhost
  POSTGRES_PASSWORD: 5astmetrics100
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}
