apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: timedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timedb
  template:
    metadata:
      labels:
        app: timedb
    spec:
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: timedb-pv-claim
      - name: {{ .Release.Name }}-files-volume
        configMap:
          name: {{ .Release.Name }}-configfiles
          defaultMode: 0744
      containers:
      - name: timescaledb
        image: ghcr.io/nceas/index-queue-monitor:v0.1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: POSTGRES_USER
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-data
        - mountPath: /docker-entrypoint-initdb.d/timedb.sql
          subPath: timedb.sql
          name: {{ .Release.Name }}-files-volume

