apiVersion: v1
kind: PersistentVolume
metadata:
  name: timedb-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/timedb-volume"

