apiVersion: batch/v1
kind: CronJob
metadata:
  name: timedb-cron
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: timedb-files-volume
            configMap:
              name: timedb-files
              defaultMode: 0744
          containers:
            - name: timedbcron
              image: ghcr.io/nceas/index-queue-monitor:v0.1.0
              imagePullPolicy: Never
              command:
              - /bin/sh
              - -c
              - date; bash /etc/timedb/insert-queue-data 1
              volumeMounts:
              - mountPath: /etc/timedb/insert-queue-data
                subPath: insert-queue-data
                name: timedb-files-volume
              - mountPath: /etc/timedb/insert-sample-data
                subPath: insert-sample-data
                name: timedb-files-volume
              env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: timedb-config
                    key: POSTGRES_PASSWORD
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: timedb-config
                    key: POSTGRES_USER
          restartPolicy: OnFailure
