apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timedb-pv-claim
  namespace: index-monitor
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
