apiVersion: v1
kind: PersistentVolume
metadata:
  name: timedb-volume
  namespace: index-monitor
spec:
  storageClassName: "hostpath"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Delete"
  hostPath:
    path: "/tmp/timedb-volume"

